### ISSUE TITLE
Why was the option --no-dev removed from missing check?

### ISSUE THREAD

**Issue by skrtheboss** [dependency-check-team/dependency-check#105]
With this [commit](https://github.com/dependency-check-team/dependency-check/commit/edfde9b5108d161a0f2ce41f4f759e29484a7940) the `--no-dev` option stoppped working, but i need it in my library, to check if `peerDependencies` are specified correctly.

**Comment by voxpelli** [comment]
It was removed to ensure the ordinary case like this one works now that the default is to check both missing and unused dependencies: https://github.com/voxpelli/node-connect-pg-simple/blob/master/package.json#L24

Thinking about it a bit extra, that fix is only needed for the case where both checks are done at once, not needed when checking missing explicitly. I'll fix.

**Comment by voxpelli** [comment]
@skrtheboss @Qard Fix released in [`4.1.0`](https://github.com/dependency-check-team/dependency-check/releases/tag/v4.1.0)

**Comment by Qard** [comment]
Thanks for the speedy turnaround! 💪
