### ISSUE TITLE
Dev Dependencies discovery question

### ISSUE THREAD

**Issue by bcomnes** [dependency-check-team/dependency-check#106]
Did `dependency-check` used to look for devDependencies/dependencies in the scripts and browser/browserify fields?  I feel like I always have to pass `--no-dev` now where I didn't used to.

**Comment by voxpelli** [comment]
It has always been the default, yes

The new change is that `--missing` and `--unused` are now both run by default, so what used to by default be just a `--missing` check is now a combined check unless one has specifically specified it to be one check or the other.

Does that explain it for you @bcomnes?

**Comment by bcomnes** [comment]
How are devDeps detected in the scripts field? Just by the name of the bins?

For example, this package:

```json
{
  "name": "gumcast-api",
  "description": "A service for generating rss feeds from gumroad subscriptions",
  "version": "0.0.0",
  "author": "Bret Comnes <bcomnes@gmail.com> (https://bret.io/)",
  "bin": "api/bin.js",
  "bugs": {
    "url": "https://github.com/bcomnes/gumcast-api/issues"
  },
  "dependencies": {
    "bent": "^1.6.0",
    "body-parser": "^1.19.0",
    "cliclopts": "^1.1.1",
    "finalhandler": "^1.1.2",
    "form-urlencoded": "^4.0.0",
    "http-hash-router": "^2.0.1",
    "jsonfeed-to-rss": "^1.1.1",
    "minimist": "^1.2.0",
    "morgan": "^1.9.1",
    "nanoassert": "^2.0.0",
    "p-connect": "^1.0.1",
    "p-map": "^3.0.0",
    "parseurl": "^1.3.3",
    "qs": "^6.7.0",
    "redirect-chain": "^1.0.1",
    "striptags": "^3.1.1",
    "trim-left": "^1.0.1",
    "trim-right": "^1.0.1"
  },
  "devDependencies": {
    "dependency-check": "^4.0.0",
    "nodemon": "^1.19.1",
    "npm-run-all": "^4.1.5",
    "standard": "^13.1.0",
    "tape": "^4.11.0"
  },
  "homepage": "https://github.com/bcomnes/gumcast-api#readme",
  "keywords": [
    "gumroad",
    "podcast"
  ],
  "license": "MIT",
  "main": "servr",
  "private": "true",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/bcomnes/gumcast-api.git"
  },
  "scripts": {
    "dev": "nodemon ./api/bin.js -- --config ./config.json",
    "dev:api": "nodemon ./api/bin.js -- --config ./config.json",
    "dev:client": "budo client/index.js",
    "start": "./api/bin.js",
    "test": "run-s test:*",
    "test:api": "tape api/**/*.test.js",
    "test:deps": "dependency-check package.json api/bin --verbose"
  }
}
```

Fails dependency check:

```console
Fail! Modules in package.json not used in code: dependency-check, nodemon, npm-run-all, standard, tape
Success! All dependencies used in the code are listed in package.json
```

I have to pass `--no-dev` to get it to pass.  

Is dependency checking cross referencing devDeps and script fields and bin names?

**Comment by voxpelli** [comment]
They are not detected in the scripts field, see: https://github.com/dependency-check-team/dependency-check/issues/14

It would be great to detect them there and you got some good points on how to go about doing so.

Want to take a stab at a PR? I can’t promise that I will be able to look into it very soon myself

**Comment by bcomnes** [comment]
Ah ok! Cool, just making sure I wasn't going crazy.  

Don't have the bandwidth at the moment, but maybe down the road.  

Browserify transforms in the browserify field are detected though?

**Comment by bcomnes** [comment]
We can close :)
