### ISSUE TITLE
Unable to configure working TSX support using detective-typescript

### ISSUE THREAD

**Issue by fatso83** [dependency-check-team/dependency-check#112]
When I run my dependency check script after adding a TSX file it exits with an error status and a very meager status message:
```
scripts/check-dependencies
'>' expected.
```

I have configured it to work with JS, JSX, TS and TSX (see below), and it does work with three of the four. But after adding my first TSX file it failed as above. 

The full config:
```shell
#!/bin/sh
EXE="$(npm bin)/dependency-check" 

"$EXE" package.json src/app.ts \
    --no-dev --unused \
    --extensions 'js,jsx:detective-es6' \
    --extensions 'ts,tsx:detective-typescript' \
    --ignore-module react-dom \
    --ignore-module mocha-teamcity-reporter \
    --ignore-module rimraf  \
    --ignore-module @types/react-dom \
    --ignore-module @types/react \
    --ignore-module @types/jss
```

All typescript with and without JSX.
```
src/app.ts
src/components/routing/ConnectedRouter.tsx
src/logging/logger.ts
src/type-declarations.d.ts
```

Full diff of the offending commit
<details>
<summary>Diff</summary>

```diff
commit 8d6b32689158fa1faadb27c7b71529bbdd15b5f9
Author: Carl-Erik Kopseng <myuser@ACME.com>
Date:   Fri Dec 13 12:01:51 2019 +0100

    Convert ConnectedRouter to typescript

diff --git a/frontend/src/components/routing/ConnectedRouter.jsx b/frontend/src/components/routing/ConnectedRouter.tsx
similarity index 81%
rename from frontend/src/components/routing/ConnectedRouter.jsx
rename to frontend/src/components/routing/ConnectedRouter.tsx
index e32e798ef..48fad3719 100644
--- a/frontend/src/components/routing/ConnectedRouter.jsx
+++ b/frontend/src/components/routing/ConnectedRouter.tsx
@@ -1,10 +1,14 @@
-import React, {Component} from 'react';
-import {Router, withRouter} from 'react-router';
-import t from 'tcomb';
-import {propTypes, ReactChildren} from 'tcomb-react';
+import React, {Component, ReactChildren} from 'react';
+import {RouteComponentProps, Router, withRouter} from 'react-router';
 
 import {locationChange, locationReplace} from '../../store/routing/routing-action';
 
+interface IOwnProps {
+  dispatch: Function;
+  children: ReactChildren;
+}
+type Props = IOwnProps & RouteComponentProps;
+
 /**
  * This is a special Router that hooks React Router actions to our injected history module
  *
@@ -20,25 +24,20 @@ import {locationChange, locationReplace} from '../../store/routing/routing-actio
  * @param children
  * @constructor
  */
-export default function ConnectedRouter({dispatch, history, children}) {
+export default function ConnectedRouter({dispatch, history, children}: Props) {
   return (
     <Router history={history}>
       <RouteChangeListener dispatch={dispatch}>{children}</RouteChangeListener>
     </Router>
   );
 }
-ConnectedRouter.propTypes = propTypes({
-  dispatch: t.Function,
-  history: t.Object,
-  children: ReactChildren
-});
 
-export class _RouteChangeListenerWithoutRouter extends Component {
+export class _RouteChangeListenerWithoutRouter extends Component<Props> {
   componentDidMount() {
     this.props.dispatch(locationChange(this.props.location));
   }
 
-  componentDidUpdate(prevProps) {
+  componentDidUpdate(prevProps: Props) {
     if (this.props.location.pathname !== prevProps.location.pathname) {
       if (this.props.history.action === 'REPLACE') {
         this.props.dispatch(locationReplace(this.props.location));
```
</details>

Are there any working examples of tsx working? Running with `DEBUG=*` doesn't really give much to work with.

**Comment by fatso83** [comment]
I see that [`detective` needs a JSX flag passed as an option for this to work](https://github.com/pahen/detective-typescript/blob/master/test/test.js#L106), but I am not able to see how this is actually [passed through the layers](https://github.com/browserify/detective/blob/master/index.js).

**Comment by blakeembrey** [comment]
Internally we're requiring the different `detective` instances for you and assuming they follow the same API (currently file contents as first argument: https://github.com/dependency-check-team/dependency-check/blob/fc2d072c27b2d14614f74db658ab629e78ba2549/index.js#L326). I think the right thing to do here, to support everything, would be to try and get all the detectives to align on supporting a `filename` option. E.g. automatically enable `jsx: true` when filename matches `\.tsx$` in `detective-typescript`. I'd start by opening an issue there, and once enabled, we can pass it through here.

**Comment by fatso83** [comment]
@blakeembrey Thank you for that feedback. Since @pahen does not have an issue tracker for that project, I will need to create a pull request for this to get any love, but for that I need to be a bit clearer on what to do. The new API you are proposing, would that look like this:

```javascript
function detective(contents, filename) {
}
```
?

Or should we open for generally accepting options as a hash for later expansion? Much like

```javascript
/**
 * @param contents {String}
 * @param options {Object}
 * @param options.filename {String} the filename of the file. Can be used to auto-enable options
 */
function detective(contents, option) {
}
```
?

**Comment by blakeembrey** [comment]
I would go for the latter, an options object. It looks like a couple already have an options object (which makes it a backward compatible change), and it’s easier to expand in the future.

**Comment by fatso83** [comment]
Hi, @pahen would prefer the users to pass in the right options, which I do understand, but would make this project harder to use, so instead of continuing that discussion I [whipped up a new module](https://github.com/fatso83/detective-tsx/commit/29eb1a126b32bcc17e4f6c2c168109971da9f5af) that does away with the whole problem: 
https://www.npmjs.com/package/@fatso83/detective-tsx

This now works for checking TSX, just do
```
    --extensions 'ts:detective-typescript' \
    --extensions 'tsx:@fatso83/detective-tsx' \
```
