### ISSUE TITLE
Issue with globs and multiple subdirectory levels

### ISSUE THREAD

**Issue by gabmontes** [dependency-check-team/dependency-check#170]
The README says globs can be used and this is the example given: `dependency-check ./test/**/*.js`.

The problem I found is that that glob matches any JavaScript file in a folder inside test (`./test/folder/file.js`) but does not match any deeper (`./test/folder/subfolder/file.js`).

To work around this, I had to specify both levels: `dependency-check ./test/*/*.js ./test/*/*/*.js`.

What could be wrong here? Thanks!!!

**Comment by gndelia** [comment]
I had the same issue, and adding the `'` worked for me 🚀
