### ISSUE TITLE
Support jspm?

### ISSUE THREAD

**Issue by unional** [dependency-check-team/dependency-check#46]
Is it possible for `dependency-check` to support `jspm`?

``` js
// package.json
{
  "jspm": {
    "dependencies": {
      "any-promise": "npm:any-promise@^1.3.0",
      "lodash": "npm:lodash@^4.13.1"
    },
}
```

`dependency-check . --unused --no-dev && dependency-check . --missing --no-dev`
fails with: 

``` sh
Success! All dependencies in package.json are used in the code
Fail! Dependencies not listed in package.json: any-promise, lodash
```

**Comment by blakeembrey** [comment]
`dependency-check` will need to adopt a plugin-like approach to make this work. Some way where we can add modules that list dependencies, and modules that parse out `require` calls.
