### ISSUE TITLE
Handle NPM `files` and `.npmignore`

### ISSUE THREAD

**Issue by blakeembrey** [dependency-check-team/dependency-check#66]
This recently come up, and has come up in the past with my own modules, but it would be cool if while traversing the dependency graph it checked the relative files against the `files` list in`package.json` and the `.npmignore` file. Somewhat related to https://github.com/maxogden/dependency-check/issues/25.

/cc @iarna what should we use the ensure we're replicating the behaviour of `files` and `.npmignore` correctly here?

**Comment by iarna** [comment]
`files` and `.npmignore` behavior is surprisingly complicated and awful. 😭 The closest thing we have to comprehensive documentation is the [files and ignores test](https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/test/tap/files-and-ignores.js) that @zkat wrote the last time we had to touch it.

That test can probably be adapted to other projects by swapping out `npm pack` and tarball extract steps for your own behavior.

**Comment by zkat** [comment]
There's also a wiki page about it that's a bit more human-consumable over at https://github.com/npm/npm/wiki/Files-and-Ignores
