### ISSUE TITLE
Support `browser` resolution

### ISSUE THREAD

**Issue by blakeembrey** [dependency-check-team/dependency-check#67]
By specing out the configuration required to make a feature like this possible, it'd be possible to re-use for other dependency files. Something like:

```ts
interface Dependency {
  entry: string
  aliases: { [name: string]: string } // Map of aliases - might want to support a wildcard syntax mapping here.
  dependencies: string[]
  devDependencies: string[]
  include: string[] // List of globs to include (`package.json` files)
  ignore: string[] // List of globs to ignore (a la `.npmignore`)
}
```

With a this complete definition supported, it should also close https://github.com/maxogden/dependency-check/issues/46 and https://github.com/maxogden/dependency-check/issues/32. Probably also https://github.com/maxogden/dependency-check/issues/25 as part of it.

**Comment by bcomnes** [comment]
Ran into this tonight. 👍
