### ISSUE TITLE
Automated tests failing on FreeBSD

### ISSUE THREAD

**Issue by duncan-bayne** [dependency-check-team/dependency-check#90]
I've cloned this repository on my FreeBSD dev machine, and am seeing the following failure when running tests:

```
$ npm install
npm WARN You are using a pre-release version of node and things may not work as expected

audited 428 packages in 2.659s
found 0 vulnerabilities

$ npm test
> dependency-check@3.1.0 test /usr/home/duncan/code/dependency-check
> standard && node cli.js test/ && node cli.js . && node cli.js . --missing --extra --no-dev -e js:detective-cjs

Failed to parse json
Unexpected token � in JSON at position 0 while parsing near '�Us
             .��q
                                                                      ...'
npm ERR! Test failed.  See above for more details.
```

Versions of things:

* Node v10.4.2-pre
* NPM 6.1.0
* FreeBSD 11.1-RELEASE GENERIC amd64

I think the warning about things not working as expected may be correct :wink:

**Comment by voxpelli** [comment]
@duncan-bayne The way to test this for someone like me would be to download some version of FreeBSD from somewhere (?) and set it up with VirtualBox – right? A Docker image isn't enough?

(Writing this on the go so I can't look these things up myself right now)

**Comment by duncan-bayne** [comment]
@voxpelli Yes - I think you can run FreeBSD inside a Docker image, but only on a FreeBSD host.  So VirtualBox would be the go there.

I'd also suggest starting off with https://www.trueos.org/ - it's FreeBSD with all the desktop goodies you'd expect.

**Comment by duncan-bayne** [comment]
I can also help w/ SSH access to an (ancient!) FreeBSD dev box I have running, if that'd help.  Email me on duncan@bayne.id.au if you'd like me to set that up.

**Comment by voxpelli** [comment]
The True OS path sounds interesting, I might also use my colleague @perlw to get some FreeBSD-help

**Comment by duncan-bayne** [comment]
@voxpelli Watch out.  You might enjoy FreeBSD so much that you become 'that guy' with the X-series ThinkPad who spends his spare time porting stuff to an obscure operating system ;)

If you're looking for FreeBSD assistance there are some [good IRC channels](https://wiki.freebsd.org/IRC/Channels) too.

**Comment by duncan-bayne** [comment]
Any luck with this?  Still happy to help where I can.

**Comment by duncan-bayne** [comment]
Closing this after ~ 3 years inactivity.
